name: souffle-haskell
synopsis: Souffle Datalog bindings for Haskell
description: Souffle Datalog bindings for Haskell.
version: 3.0.0
homepage: https://github.com/luc-tielen/souffle-haskell#README.md
license: MIT
author: Luc Tielen
maintainer: luc.tielen@gmail.com
copyright: 2020 Luc Tielen
category: Logic Programming, Foreign Binding, Bindings
github: luc-tielen/souffle-haskell
extra-source-files:
  - README.md
  - CHANGELOG.md
  - LICENSE
  - cbits/**/*.h
  - cbits/*.cpp
  - cbits/souffle/LICENSE

dependencies:
  - base >= 4.12 && < 5
  - mtl >= 2.0 && < 3
  - template-haskell >= 2 && < 3
  - type-errors-pretty >= 0.0.1.0 && < 1
  - text >= 1.0 && < 2
  - text-short >= 0.1.3 && < 1
  - containers >= 0.6.2.1 && < 1
  - vector <= 1.0
  - array <= 1.0
  - deepseq >= 1.4.4 && < 2
  - directory >= 1.3.3 && < 2
  - filepath  >= 1.4.2 && < 2
  - temporary >= 1.3 && < 2
  - process >= 1.6 && < 2
  - bytestring

default-extensions:
  - OverloadedStrings
  - LambdaCase
  - ScopedTypeVariables

ghc-options:
  - -Wall
  - -Weverything
  - -Wno-safe
  - -Wno-unsafe
  - -Wno-implicit-prelude
  - -Wno-missed-specializations
  - -Wno-all-missed-specializations
  - -Wno-missing-import-lists
  - -Wno-type-defaults
  - -Wno-missing-local-signatures
  - -Wno-monomorphism-restriction
  - -Wno-missing-deriving-strategies
  - -Wno-prepositive-qualified-module
  - -Wno-missing-safe-haskell-mode
  - -optP-Wno-nonportable-include-path
  - -fhide-source-paths
  - -fno-show-valid-hole-fits
  - -fno-sort-valid-hole-fits

cxx-options:
  - -std=c++17

include-dirs:
  - cbits
  - cbits/souffle

install-includes:
  - souffle/CompiledSouffle.h
  - souffle/CompiledTuple.h
  - souffle/RamTypes.h
  - souffle/RecordTable.h
  - souffle/SignalHandler.h
  - souffle/SouffleInterface.h
  - souffle/SymbolTable.h
  - souffle/utility/MiscUtil.h
  - souffle/utility/tinyformat.h
  - souffle/utility/ParallelUtil.h
  - souffle/utility/StreamUtil.h
  - souffle/utility/ContainerUtil.h
  - souffle/datastructure/Brie.h
  - souffle/utility/CacheUtil.h
  - souffle/datastructure/EquivalenceRelation.h
  - souffle/datastructure/LambdaBTree.h
  - souffle/datastructure/BTree.h
  - souffle/datastructure/PiggyList.h
  - souffle/datastructure/UnionFind.h
  - souffle/datastructure/Table.h
  - souffle/io/IOSystem.h
  - souffle/io/ReadStream.h
  - souffle/io/SerialisationStream.h
  - souffle/utility/json11.h
  - souffle/utility/StringUtil.h
  - souffle/io/ReadStreamCSV.h
  - souffle/utility/FileUtil.h
  - souffle/io/gzfstream.h
  - souffle/io/ReadStreamJSON.h
  - souffle/io/WriteStream.h
  - souffle/io/WriteStreamCSV.h
  - souffle/io/WriteStreamJSON.h
  - souffle/io/ReadStreamSQLite.h
  - souffle/io/WriteStreamSQLite.h
  - souffle/utility/EvaluatorUtil.h
  - souffle/utility/FunctionalUtil.h

library:
  source-dirs: lib
  cxx-sources: cbits/*.cpp
  cxx-options:
    - -Wall
  when:
    - condition: os(linux)
      extra-libraries: stdc++
  generated-other-modules:
    - Paths_souffle_haskell

tests:
  souffle-haskell-test:
    main: test.hs
    source-dirs: tests
    cxx-sources: tests/fixtures/*.cpp
    when:
      - condition: os(darwin)
        extra-libraries: c++
    dependencies:
      - hspec >= 2.6.1 && < 3.0.0
      - hspec-hedgehog == 0.*
      - hedgehog == 1.*
      - neat-interpolation == 0.*
      - souffle-haskell
    build-tools:
      - hspec-discover == 2.*
    cxx-options:
      - -D__EMBEDDED_SOUFFLE__

benchmarks:
  souffle-haskell-benchmarks:
    main: bench.hs
    source-dirs: benchmarks
    cxx-sources: benchmarks/fixtures/*.cpp
    when:
      - condition: os(darwin)
        extra-libraries: c++
    dependencies:
      - souffle-haskell
      - criterion
    cxx-options:
      - -D__EMBEDDED_SOUFFLE__
      - -std=c++17
      - -march=native
    ghc-options:
      - +RTS -N1 -RTS  # Run benchmarks sequentially (parallel is not safe!)
