name: souffle-haskell
synopsis: Souffle Datalog bindings for Haskell
description: Souffle Datalog bindings for Haskell.
version: 3.5.1
homepage: https://github.com/luc-tielen/souffle-haskell#README.md
license: MIT
author: Luc Tielen
maintainer: luc.tielen@gmail.com
copyright: 2022 Luc Tielen
category: Logic Programming, Foreign Binding, Bindings
github: luc-tielen/souffle-haskell
extra-source-files:
  - README.md
  - CHANGELOG.md
  - LICENSE
  - cbits/**/*.h
  - cbits/*.cpp
  - cbits/souffle/LICENSE

dependencies:
  - base >= 4.12 && < 5
  - text >= 1.0 && < 2
  - vector <= 1.0

default-extensions:
  - DerivingStrategies
  - FlexibleContexts
  - LambdaCase
  - OverloadedStrings
  - ScopedTypeVariables
  - StandaloneKindSignatures

ghc-options:
  - -Wall
  - -Weverything
  - -Wno-safe
  - -Wno-unsafe
  - -Wno-implicit-prelude
  - -Wno-missed-specializations
  - -Wno-all-missed-specializations
  - -Wno-missing-import-lists
  - -Wno-type-defaults
  - -Wno-missing-local-signatures
  - -Wno-monomorphism-restriction
  - -Wno-prepositive-qualified-module
  - -Wno-missing-safe-haskell-mode
  - -optP-Wno-nonportable-include-path
  - -fhide-source-paths
  - -fno-show-valid-hole-fits
  - -fno-sort-valid-hole-fits

cxx-options:
  - -std=c++17

include-dirs:
  - cbits
  - cbits/souffle

install-includes:
  - souffle/CompiledSouffle.h
  - souffle/RamTypes.h
  - souffle/RecordTable.h
  - souffle/utility/span.h
  - souffle/SignalHandler.h
  - souffle/SouffleInterface.h
  - souffle/SymbolTable.h
  - souffle/utility/MiscUtil.h
  - souffle/utility/General.h
  - souffle/utility/Iteration.h
  - souffle/utility/Types.h
  - souffle/utility/tinyformat.h
  - souffle/datastructure/BTreeDelete.h
  - souffle/datastructure/BTreeUtil.h
  - souffle/utility/CacheUtil.h
  - souffle/utility/ContainerUtil.h
  - souffle/utility/DynamicCasting.h
  - souffle/utility/ParallelUtil.h
  - souffle/datastructure/Brie.h
  - souffle/utility/StreamUtil.h
  - souffle/datastructure/EquivalenceRelation.h
  - souffle/datastructure/LambdaBTree.h
  - souffle/datastructure/BTree.h
  - souffle/datastructure/PiggyList.h
  - souffle/datastructure/UnionFind.h
  - souffle/datastructure/RecordTableImpl.h
  - souffle/datastructure/ConcurrentFlyweight.h
  - souffle/datastructure/ConcurrentInsertOnlyHashMap.h
  - souffle/datastructure/SymbolTableImpl.h
  - souffle/datastructure/Table.h
  - souffle/io/IOSystem.h
  - souffle/io/ReadStream.h
  - souffle/io/SerialisationStream.h
  - souffle/utility/StringUtil.h
  - souffle/utility/json11.h
  - souffle/io/ReadStreamCSV.h
  - souffle/utility/FileUtil.h
  - souffle/io/gzfstream.h
  - souffle/io/ReadStreamJSON.h
  - souffle/io/WriteStream.h
  - souffle/io/WriteStreamCSV.h
  - souffle/io/WriteStreamJSON.h
  - souffle/io/ReadStreamSQLite.h
  - souffle/io/WriteStreamSQLite.h
  - souffle/utility/EvaluatorUtil.h
  - souffle/utility/EvaluatorUtil.h

library:
  source-dirs: lib
  cxx-sources: cbits/*.cpp
  cxx-options:
    - -Wall
  when:
    - condition: os(linux)
      extra-libraries: stdc++
  generated-other-modules:
    - Paths_souffle_haskell
  dependencies:
    - mtl >= 2.0 && < 3
    - deepseq >= 1.4.4 && < 2
    - filepath  >= 1.4.2 && < 2
    - process >= 1.6 && < 2
    - bytestring >= 0.10.10 && < 1
    - text-short >= 0.1.3 && < 1
    - array <= 1.0
    - profunctors >= 5.6.2 && < 6
    - directory >= 1.3.3 && < 2
    - temporary >= 1.3 && < 2

tests:
  souffle-haskell-test:
    main: test.hs
    source-dirs: tests
    cxx-sources: tests/fixtures/*.cpp
    when:
      - condition: os(darwin)
        extra-libraries: c++
    dependencies:
      - hspec >= 2.6.1 && < 3.0.0
      - hspec-hedgehog == 0.*
      - hedgehog == 1.*
      - text-short >= 0.1.3 && < 1
      - array <= 1.0
      - profunctors >= 5.6.2 && < 6
      - directory >= 1.3.3 && < 2
      - temporary >= 1.3 && < 2
      - souffle-haskell
    cxx-options:
      - -D__EMBEDDED_SOUFFLE__
    ghc-options:
      - -Wno-missing-kind-signatures
      - -Wno-operator-whitespace

benchmarks:
  souffle-haskell-benchmarks:
    main: bench.hs
    source-dirs: benchmarks
    cxx-sources: benchmarks/fixtures/*.cpp
    when:
      - condition: os(darwin)
        extra-libraries: c++
    dependencies:
      - souffle-haskell
      - criterion
      - deepseq >= 1.4.4 && < 2
    cxx-options:
      - -D__EMBEDDED_SOUFFLE__
      - -std=c++17
      - -march=native
    ghc-options:
      - +RTS -N1 -RTS # Run benchmarks sequentially (parallel is not safe!)
